#!/usr/bin/env sh

set -e

LOG_PREFIX="systemd-boot-btrfs"
err() {
    bug_report="If you think an error has occurred, please file a bug report at \"https://github.com/okmans/systemd-boot-btrfs\""
    printf "%s: Error: %s %s\n" "$LOG_PREFIX" "$*" "${bug_report}" >&2
    exit 1
}

BOOT_DIR="/boot"

initramfs_img="$(find "${BOOT_DIR}" -maxdepth 1 -type f \
    \( -name 'initrd*' -o -name 'initramfs*' \) -print0 -quit)"
[ ! -e "${initramfs_img}" ] && err "no initramfs image was found."

# Check if systemd-boot is the default bootloader
systemd_boot_efi="$(find "${BOOT_DIR}" -type f \
    -name 'systemd*.efi' -print0 -quit)"
[ ! -e "${systemd_boot_efi}" ] && \
    err "systemd-boot is not the default bootloader."

# Check if systemd loader entries directory exists
entries_dir="$(find "${BOOT_DIR}" -type d \
    -path '*/loader/entries' -print0 -quit)"
[ ! -d "${entries_dir}" ] && err "systemd entries directory does not exist."

# Find out a template config 'main*.conf' or the old lead config
base_conf="$(find "${entries_dir}" -maxdepth 1 -type f \
    -name 'main-*.conf' -print0 -quit)"
[ ! -e "${base_conf}" ] && {
    base_conf="$(find "${entries_dir}" -maxdepth 1 -type f \
        -name '*.conf' \
        -printf '%T@ %f\n\0' \
        | sort -n | head -1 | awk '{print $NF}')"
}

[ -z "${base_conf}" ] && \
    err "could not find main-*.conf or the old lead config.\n"

#if ! grep -q -i -e 'rootflags=' "${entries_dir}/${base_conf}" ; then
#    printf "your main boot entry file missing the option 'rootflags'.\n"
#    exit 1
#fi

boot_snap_name="$(basename -s '.conf' "${base_conf}")"
boot_snap_suffix="-snap.conf"

# Count non-snapshot boot entries
boot_entries_count="$(find "${entries_dir}" -maxdepth 1 -type f \
    \( -name '*.conf' -a \! -name "*${boot_snap_suffix}" \) | wc -l)"

# Remove existent snapshot entries
find "${entries_dir}" -maxdepth 1 -type f \
    -name "${boot_snap_name}*${boot_snap_suffix}" -delete

SNAPSHOTS_DIR="/.snapshots"
get_btrfs_snapshots() {
    btrfs subvolume list -s -o "${SNAPSHOTS_DIR}" | awk '{printf "%s\0", $NF}'
}

sed_check="$(grep -n -E -e 'title|sort-key|options' "${entries_dir}/${base_conf}" | cut -d ' ' -f 1)"

sed_row_title="$(echo "${sed_check}" | grep -i -E -o -e '[0-9]+:title' | cut -d : -f 1)"
sed_row_sort="$(echo "${sed_check}" | grep -i -E -o -e '[0-9]+:sort-key' | cut -d : -f 1)"
sed_row_options="$(echo "${sed_check}" | grep -i -E -o -e '[0-9]+:options' | cut -d : -f 1)"

snapshots_path="/.snapshots"
snapper_info="info.xml"
read_info_xml() {
    for i in $1; do
        title=$(awk -F'[<>]' '/<num>|type|date|description/{printf $3OFS} END {print ""}' "$i")
        snap_title="Snapshot: ${title}"
        number=$(echo "${title}" | awk '{print $2}')

        number=$((number + boot_entries_count))
        if [ ${#number} -lt 2 ] ; then
            number="0${number}"
        fi

        snap_subvol="$(printf '%s\n' "$1" | sed -E -e 's|\/\.|@|' -e 's|info\.xml|snapshot|')"
        snap_cfg="${entries_dir}/${boot_snap_name}-${number}${boot_snap_suffix}"

        sed -E \
            -e "$sed_row_title s|title\s.*|title ${snap_title}|" \
            -e "$sed_row_sort s|sort-key\s.*|sort-key ~${number}|" \
            -e "$sed_row_options s|rootflags=subvol=[\/@a-zA-Z0-9]+\s*|rootflags=subvol=${snap_subvol} overlayroot=tmpfs |" \
            "${entries_dir}/${base_conf}"
#            \
            >"${snap_cfg}"
    done | column -t
}

snapshot_infos="$(find "${SNAPSHOTS_DIR}"/* -maxdepth 1 -type f -name "${snapper_info}" -print0)"
set -x
IFS='\0' for si in "${snapshot_infos}"; do
    read_info_xml "$si"
done
